import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-[var(--bg)] text-[var(--ink)]">
      <div className="mx-auto max-w-5xl p-6 lg:p-10">
        <div className="mb-6">
          <p className="text-sm font-semibold text-[var(--accent)]">Legal</p>
          <h1 className="text-3xl font-semibold">Disclaimer</h1>
        </div>

        <section className="space-y-5 rounded-3xl border border-[var(--border)] bg-[var(--panel)] p-6 shadow-sm">
          <p className="text-sm text-[var(--muted)]">
            The content generated by WimpyAI is provided for general informational purposes only. It may not always be complete, accurate, or suitable for your specific situation.
          </p>
          <div className="space-y-4 text-sm leading-7 text-[var(--ink)]">
            <p>
              You should verify critical details independently and avoid relying solely on the assistant for legal, medical, financial, or safety-critical decisions.
            </p>
            <p>
              We are not responsible for actions you take based on generated content. Use the service responsibly.
            </p>
            <p>
              If you need professional advice, consult a licensed expert in the relevant field.
            </p>
          </div>
        </section>

        <div className="mt-8">
          <Link href="/profile" className="text-sm font-semibold text-[var(--accent)] hover:underline">
            ← Back to profile
          </Link>
        </div>
      </div>
    </main>
  );
}
